name: "CI"
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: "ubuntu-latest"
    steps:
    - name: Setup Go environment
      uses: actions/setup-go@v3
      with:
        go-version: "1.18.x"

    - name: Install linters
      run: |
        go install golang.org/x/tools/cmd/goimports@latest
        go install honnef.co/go/tools/cmd/staticcheck@latest

    # Checks-out the repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Run linters
    - name: Run go vet
      run: go vet ./...
    - name: Run goimports
      run: test -z $(find . -name '*.go' -type f | xargs goimports -e -d | tee /dev/stderr)
    - name: Run staticcheck
      run: staticcheck ./...

  test:
    name: "Test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # use max/min supported Go versions
        go-version: ["1.18.x", "1.13.x"]

    steps:
    - name: Setup Go environment
      id: setup-go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    # Checks-out the repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # Run tests
    - run: go test -v -cover -race ./...

  build:
    name: "Build Calculator (${{ matrix.target.os }}, ${{ matrix.go-version }})"
    runs-on: ${{ matrix.target.host || 'ubuntu-latest' }}
    strategy:
      fail-fast: false
      matrix:
        # use max/min supported Go versions
        go-version: ["1.18.x", "1.13.x"]
        target:
          - os: linux
          - os: windows
            ext: .exe
          - os: freebsd
          - os: android
            args: -app-id calc.${GITHUB_SHA}
          - os: darwin
            args: -app-id calc.${GITHUB_SHA}
            host: macos-latest
            requires-darwin-image: true
          - os: ios
            args: -app-id calc.${GITHUB_SHA}
            host: macos-latest
            requires-darwin-image: true

    steps:
      - name: Setup Go environment
        id: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: fyne-cross

      - name: Checkout fyne-io/calculator
        uses: actions/checkout@v2
        with:
          repository: fyne-io/calculator
          path: calculator

      - name: Cache build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/.cache/fyne-cross
          key: ${{ runner.os }}-build-cache-${{ hashFiles('**/go.sum') }}

      - name: Install Fyne-cross
        working-directory: fyne-cross
        run: go install

      - name: Build Darwin image
        if: ${{ matrix.target.requires-darwin-image }}
        run: |
          fyne-cross \
            darwin-image \
            -xcode-path $(xcode-select -p)
            
      - name: Build
        working-directory: calculator
        run: |
          fyne-cross \
            ${{ matrix.target.os }} \
            ${{ matrix.target.args }} \
            -debug -no-cache \
            -name calculator${{ matrix.target.ext }}
